const members = [
    { name: "Ken Agwaro", status: "Active" },
    { name: "Boaz Nundu", status: "Active" },
    { name: "Bernard Odhiambo", status: "Active" },
    { name: "Daniel Rakoro", status: "Active" },
    { name: "Joshua Oraga", status: "Active" },
    { name: "Isaack Onyonyi", status: "Active" },
    { name: "Amos Otieno", status: "Active" },
    { name: "Pr BOG Dianga", status: "Active" },
    { name: "Fredrick Odoyo", status: "Active" },
    { name: "Martin Nyakiamo", status: "Active" },
    { name: "Amos K.Sikweya", status: "Active" },
    { name: "Josephine Mbeo", status: "Active" },
    { name: "Kennedy Onyonyi", status: "Active" },
    { name: "Daniel Nyadenda", status: "Active" },
    { name: "Mark Matunga", status: "Active" },
    { name: "Caleb Ginarah", status: "Deceased" },
    { name: "Everline Antone", status: "Active" },
    { name: "Otiob Obuogo", status: "Active" },
    { name: "Omondi Lukas Kingo", status: "Active" },
    { name: "Moses Nyakwada", status: "Active" },
    { name: "Kamaliza Majengo", status: "Active" },
    { name: "Riat London", status: "Active" },
    { name: "Edwins Otieno", status: "Active" },
    { name: "Clifford Maginga", status: "Active" },
    { name: "Chwaks Maurice Obote", status: "Active" },
    { name: "Gilbert Omogi", status: "Active" },
    { name: "Paul Sungu", status: "Active" },
    { name: "Amos Odero-Kwasi", status: "Active" },
    { name: "Judy Kamaria", status: "Active" },
    { name: "Walter Bunde", status: "Active" },
    { name: "Elvis Oyugi", status: "Active" },
    { name: "Washington Owuor Khoi", status: "Active" },
    { name: "Nicholas Omukinga Walaga", status: "Active" },
    { name: "Daniel Oreri", status: "Active" },
    { name: "Wambo Otieno", status: "Active" },
    { name: "Walter Mtindi", status: "Active" },
    { name: "Maureen Okeyo Orlale", status: "Active" },
    { name: "Jack Kasole", status: "Active" },
    { name: "Esther Atieno Ouma", status: "Active" },
    { name: "Peter Ongoro", status: "Active" },
    { name: "Elizar Wambo", status: "Active" },
    { name: "Elizabeth Mbeo", status: "Active" },
    { name: "Pius Olima Okelo", status: "Active" },
    { name: "Daniel Okumu", status: "Active" },
    { name: "Mzee Obadiah Wasonga", status: "Active" },
    { name: "Jane Otadoh", status: "Active" },
    { name: "Emmans Otadoh", status: "Active" },
    { name: "Dennish Matunga", status: "Active" },
    { name: "Michael Ang'anyo Onyango", status: "Active" },
    { name: "Samson Dianga", status: "Active" },
    { name: "Timons Sigo", status: "Active" },
    { name: "Jeremiah Okumu", status: "Active" },
    { name: "George Abongo Masinga", status: "Withdrawn membership" },
    { name: "Daniel Odoyo", status: "Active" },
    { name: "Maureen Akinyi Orifa", status: "Active" },
    { name: "Job Nguka Orifa", status: "Active" },
    { name: "Maurice Okoth Amisi", status: "Active" },
    { name: "Dr Jane Amisi", status: "Active" },
    { name: "Philster Aber", status: "Active" },
    { name: "Daniel Omogi", status: "Active" },
    { name: "Philemon Walwanda", status: "Active" },
    { name: "Patrick Lumumba Ogutu", status: "Active" },
    { name: "Raph Abiero", status: "Active" },
    { name: "Victor Okwach Okongo", status: "Active" },
    { name: "Melvin Akinyi Okwach", status: "Active" },
    { name: "Moses Ogutu", status: "Active" },
    { name: "Tobias Ogutu Maziga", status: "Active" },
    { name: "Phelix Odero", status: "Active" },
    { name: "Lawrence Magware", status: "Active" },
    { name: "Kasujaa Onyonyi", status: "Active" },
    { name: "Fredrick Ogot Ochieng", status: "Active" },
    { name: "Obote Okeyo", status: "Deceased" },
    { name: "Hamisi okeyo", status: "Active" },
    { name: "Lucy okeyo", status: "Active" },
    { name: "Kevin Agwaro okeyo", status: "Active" },
    { name: "Paul Nyainda", status: "Active" },
    { name: "Lucy Ngure Okeyo", status: "Active" },
    { name: "Achieng Okeyo", status: "Active" },
    { name: "Stacy Ceclia Agwaro", status: "Active" },
    { name: "Miriam Agwaro", status: "Active" },
    { name: "James oyuko Robert", status: "Active" },
    { name: "Peter Tosh Agwaro", status: "Active" },
    { name: "William Nyakwada", status: "Active" },
    { name: "Elijah Wasonga", status: "Active" },
    { name: "Samwel Walwanda", status: "Active" },
    { name: "Irene Ouma", status: "Active" },
    { name: "Helekia Ojwang", status: "Active" },
    { name: "Nicholas Otieno Adolph", status: "Active" },
    { name: "Molly Aoko Kamaliza", status: "Active" },
    { name: "John Osodo", status: "Active" },
    { name: "Eliud Kiche", status: "Active" },
    { name: "Nicholas Okech Odhiambo", status: "Active" },
    { name: "Michael Odoyo Dadiah", status: "Active" },
    { name: "Aloyce Walaga", status: "Active" },
    { name: "Alex Sungu Munyirwa", status: "Active" },
    { name: "Aloyce Julius", status: "Active" },
    { name: "Oport Obuogo", status: "Active" },
    { name: "Ayub Ochieng Otieno", status: "Active" },
    { name: "Christopher Omondi", status: "Active" },
    { name: "Peter Okoth Omogi", status: "Active" },
    { name: "Jane A.Ombajo", status: "Active" },
    { name: "Samwel Karan", status: "Active" },
    { name: "Humphrey Omondi Dianga", status: "Active" },
    { name: "Dorothy Oluoch", status: "Active" },
    { name: "Alphonce Muomba", status: "Active" },
    { name: "John Kujah", status: "Active" },
    { name: "Judith Namubiri", status: "Active" },
    { name: "Tom Ouma", status: "Active" },
    { name: "Robinson Okeyo", status: "Active" },
    { name: "John Okado Otieno", status: "Active" },
    { name: "George Okoro", status: "Active" },
    { name: "Paul Ongulu", status: "Active" },
    { name: "Dr Judith Nyunja-Riat", status: "Active" },
    { name: "Daniel Okech", status: "Active" },
    { name: "Tom Okeyo", status: "Active" },
    { name: "Beatrice A.Rakoro", status: "Active" },
    { name: "George Sikweya", status: "Active" },
    { name: "Odero John Keri", status: "Active" },
    { name: "Michael Magulu Okomo", status: "Active" },
    { name: "Joshiah Oyuko", status: "Active" },
    { name: "Matilda Wambua Odera", status: "Active" },
    { name: "Alphonce Odera", status: "Active" },
    { name: "Meshack Ogweno Osodo", status: "Active" },
    { name: "Gilbert Oloo", status: "Active" },
    { name: "Ezekiel Odhiambo", status: "Active" },
    { name: "Michael Okongo", status: "Active" },
    { name: "Joe Kiduma Obogno", status: "Active" },
    { name: "Kennedy Magumba", status: "Active" },
    { name: "Kennedy Otieno Olum", status: "Active" },
    { name: "Elvis Owuor Mau", status: "Active" },
    { name: "George K Ojwang", status: "Active" },
    { name: "Alvin Odhiambo", status: "Active" },
    { name: "Collins Odhiambo", status: "Active" },
    { name: "Kenedy Ochola", status: "Active" },
    { name: "Carolyne Muringa", status: "Active" },
    { name: "Joy Mattah", status: "Active" },
    { name: "Sylvia Nyakwada", status: "Active" },
    { name: "Iscah Obuogoh Hohloch", status: "Active" },
    { name: "Elizabeth Otiob Obuogo", status: "Active" },
    { name: "Mary Mbeo", status: "Active" },
    { name: "Paul Nick Odhiambo", status: "Active" },
    { name: "Falconery Jim", status: "Active" },
    { name: "Elizabeth Manyala", status: "Active" },
    { name: "Eng.Samwel Odambatafwa", status: "Active" },
    { name: "Bernard Odhiambo Matunga", status: "Active" },
    { name: "Wycliffe Odhiambo", status: "Active" },
    { name: "Berryl Higgins", status: "Active" },
    { name: "George Kenneth Ouma", status: "Active" },
    { name: "Rose A.Ojwang", status: "Active" },
    { name: "Paul Odhiambo Odongo", status: "Active" },
    { name: "Nicholas Otieno Seko", status: "Active" },
    { name: "Jack Obonyo", status: "Active" },
    { name: "Samwel Okoth", status: "Active" },
    { name: "Stanley Kuja", status: "Active" },
    { name: "Doreen Oport", status: "Active" },
    { name: "Emmanuel Sungu", status: "Active" },
    { name: "Jane Yongo", status: "Active" },
    { name: "Martin Agida", status: "Active" },
    { name: "Rose A. Odambatafwa", status: "Active" },
    { name: "Dr Samwel Oyugi", status: "Active" },
    { name: "Joyce Lumumba", status: "Active" },
    { name: "Beatrice Okeyo", status: "Active" },
    { name: "Peter Agwaro", status: "Deceased" },
    { name: "Kennedy Oluoch Fungo", status: "Active" },
    { name: "Dennis Ombaka", status: "Active" },
    { name: "Nellie Achieng Dande", status: "Active" },
    { name: "Samwel Ogutu", status: "Deceased" },
    { name: "Erick OUMA Oluoch", status: "Active" },
    { name: "Daniel O.Amisi", status: "Active" },
    { name: "Liz Walwanda Ward", status: "Active" },
    { name: "Dr.Joshwa Odoyo Ojwang", status: "Active" },
    { name: "Kamala Ogweno", status: "Active" },
    { name: "George C.Oyugi", status: "Active" },
    { name: "Wafula Orifa", status: "Active" },
    { name: "Nancy Okuganya", status: "Active" },
    { name: "Achieng Kiwasu Mackonya", status: "Active" },
    { name: "Wilson Ogweno", status: "Active" },
    { name: "Phelix Ochieng Orifa", status: "Active" },
    { name: "Dr Oscar Kambona Ouma", status: "Active" },
    { name: "Martin Ouma", status: "Active" },
    { name: "Moshe D Ojwang", status: "Active" },
    { name: "George Opiyo Aimo", status: "Active" },
    { name: "James Okelo Aimo", status: "Active" },
    { name: "Leonard Onyonyi", status: "Active" },
    { name: "Grace Ouma", status: "Active" },
    { name: "Kenyatta Otieno", status: "Active" },
    { name: "Elekia Odari", status: "Active" },
    { name: "Eric Ogola", status: "Active" },
    { name: "David Kiruy", status: "Active" },
    { name: "Felix Owuor", status: "Active" },
    { name: "Ogweno Omolo Tembo", status: "Active" },
    { name: "Erick Okeyo Owuor", status: "Active" },
    { name: "Mildred Ochieng", status: "Active" },
    { name: "Paul Ojwang", status: "Active" },
    { name: "Patroba Tobias", status: "Active" },
    { name: "Fidel Onyonyi", status: "Active" },
    { name: "Felix Marowe", status: "Active" },
    { name: "Afline Aber", status: "Active" },
    { name: "George Odhiambo Opiyo", status: "Active" },
    { name: "Moses Otieno Mumberi", status: "Active" },
    { name: "Sam Okoth", status: "Active" },
    { name: "Daniel Otieno", status: "Active" },
    { name: "Suleiman Ogweno Balaka", status: "Active" },
    { name: "Harriet Otieno", status: "Active" },
    { name: "Nicholas Otieno Musa", status: "Active" },
    { name: "Leonard Ngeso Otunga", status: "Active" },
    { name: "Mawualo Dianga", status: "Active" },
    { name: "Washington Nyaura Otieno", status: "Active" },
    { name: "Warren Akoth", status: "Active" },
    { name: "Martin Osodo", status: "Active" },
    { name: "Francis Onyango Walter", status: "Active" },
    { name: "Michael Ogweno Amisi", status: "Active" },
    { name: "Okoth Kagungu", status: "Active" },
    { name: "Francisca Yopon", status: "Active" },
    { name: "Erick Odhiambo", status: "Active" },
    { name: "Party Muringa", status: "Active" },
    { name: "Maurice Oduk", status: "Active" },
    { name: "Thomas Kaganda", status: "Active" },
    { name: "Suleiman Adagala", status: "Active" },
    { name: "David Obiero Wachara", status: "Active" },
    { name: "John Ouma Daniel", status: "Active" },
    { name: "Fenny Mboya", status: "Active" },
    { name: "Janet Alloys", status: "Active" },
    { name: "Caroline Asimba", status: "Active" },
    { name: "Calvince Orifa", status: "Active" },
    { name: "Dr Phelgoma Otieno", status: "Active" },
    { name: "Cosolata Odinya", status: "Active" },
    { name: "Samwel Wachara", status: "Active" },
    { name: "Amos Kings Agwaro", status: "Active" },
    { name: "Joshua Otieno Agwaro", status: "Active" },
    { name: "Joe Orifa", status: "Active" },
    { name: "Didacus Masanga", status: "Active" },
    { name: "Samwel Bojwang", status: "Active" },
    { name: "Collins Makemo", status: "Active" },
    { name: "Francis Ngala", status: "Active" },
    { name: "Sheila Ode", status: "Active" },
    { name: "John Osogo", status: "Active" },
    { name: "Elizabeth Oguta", status: "Active" },
    { name: "Nyakwamba John", status: "Active" },
    { name: "Hanington Odera", status: "Active" },
    { name: "Eld.Arphaxad Ayako Mugambwa", status: "Active" },
    { name: "James Orwa", status: "Active" },
    { name: "Tom Raila Ojwang", status: "Active" },
    { name: "Concord Dennis Achapa", status: "Active" },
    { name: "Johana Mackonya", status: "Active" },
    { name: "Gordon Ka'chola", status: "Active" },
    { name: "Asken Agwaro", status: "Active" },
    { name: "Mishael Ouma Orifa", status: "Active" },
    { name: "Hillary Okello Odingo", status: "Active" },
    { name: "Mary Akinyi Okech", status: "Active" },
    { name: "Silas Jakakiimba", status: "Active" },
    { name: "Dennis Otieno", status: "Active" },
    { name: "Bernard Okello Onyango", status: "Active" },
    { name: "Maureen Okomo Otado", status: "Active" },
    { name: "Phimason Mattah", status: "Active" },
    { name: "Tuko Narkiso", status: "Active" },
    { name: "Faith Weke", status: "Active" },
    { name: "Hillary Odhiambo", status: "Active" },
    { name: "George Odero", status: "Active" },
    { name: "Zeph Oyugi", status: "Active" },
    { name: "Eld.Ochieng Mbeo", status: "Active" },
    { name: "Daniel Otieno Okech", status: "Active" },
    { name: "Bernard Perez Nyadenda", status: "Active" },
    { name: "Ruth Balah", status: "Active" },
    { name: "Alphonce Lingungu", status: "Active" },
    { name: "Michelle Mbeo", status: "Active" },
    { name: "Gilbert Mbeo", status: "Active" },
    { name: "Irene Mbeo", status: "Active" },
    { name: "Dianne Mbeo", status: "Active" },
    { name: "John Mbeo", status: "Active" },
    { name: "Polleyn Mbeo", status: "Active" },
    { name: "Walter Ginara", status: "Active" },
    { name: "Kennedy Manyala", status: "Active" },
    { name: "Meshack Koballa", status: "Active" },
    { name: "Lydia Akinyi Koballa", status: "Active" },
    { name: "Olga Oguta", status: "Active" },
    { name: "Yvonne Otieno", status: "Active" },
    { name: "Dennis Aber", status: "Active" },
    { name: "Julius Ogutu Francis", status: "Active" },
    { name: "Geoffrey Owuor", status: "Active" },
    { name: "Maurice Odamabatafwa", status: "Active" },
    { name: "Isaack Maziga", status: "Active" },
    { name: "Isaiha Oloo", status: "Active" },
    { name: "Maureen Ombaki Maziga", status: "Active" },
    { name: "Aloyce Odero Rakoro", status: "Active" },
    { name: "Paul David Ololo", status: "Active" },
    { name: "Denis Amisi", status: "Active" },
    { name: "Pius Ochola", status: "Active" },
    { name: "Denis Oluoch Ginara", status: "Active" },
    { name: "Sherald Amisi Akama", status: "Active" },
    { name: "Gabriel Ojwaya", status: "Active" },
    { name: "Harrison Osodo Oluoch", status: "Active" },
    { name: "Johnson Ojwang", status: "Active" },
    { name: "Beryl Akoth Marowe", status: "Active" },
    { name: "Nicholas Oluoch", status: "Active" },
    { name: "Evans Odero Wasonga", status: "Active" },
    { name: "Celestine Makongo", status: "Active" },
    { name: "Beatrice Adhiambo Dianga", status: "Active" },
    { name: "Martin Ndege", status: "Active" },
    { name: "Stanley Odhiambo", status: "Active" },
    { name: "Samuel Kinya", status: "Active" },
    { name: "Harizon Ochola", status: "Active" },
    { name: "Steve Biko Otieno", status: "Active" },
    { name: "Mark Odhiambo", status: "Active" },
    { name: "Narkiso Okinyi Onyango", status: "Active" },
    { name: "Vincent Onyonyi", status: "Active" },
    { name: "Rasto Ogutu", status: "Active" },
    { name: "Michael Omogi Osodo", status: "Active" },
    { name: "Dr JaneAnyasa Okomo Otado", status: "Active" },
    { name: "Pamela Mbesa Wilson", status: "Active" },
    { name: "Dr Sharon Anyango Manyalla", status: "Active" },
    { name: "Joshua Onyango", status: "Active" },
    { name: "Andrew Lawrence Abwoga", status: "Active" },
    { name: "Ockebe Akinyi", status: "Active" },
    { name: "John G Odhiambo", status: "Active" },
    { name: "Kennedy Olumbe Ogweno", status: "Active" },
    { name: "Gregory Ogola", status: "Active" },
    { name: "Sophie Otadoh", status: "Active" },
    { name: "Lawrence Okomo Otado", status: "Active" },
    { name: "Abigael Lumumba", status: "Active" },
    { name: "George Wachara", status: "Active" },
    { name: "George Otieno Achapa", status: "Active" },
    { name: "Convine Nyamwaya", status: "Active" },
    { name: "Veronica Aono", status: "Active" },
    { name: "Lordficus Okeyo Odhiambo", status: "Active" },
    { name: "Evelyne Owuor", status: "Active" },
    { name: "Jimmy Carter Owuato", status: "Active" },
    { name: "Phelix Odongo Walwanda", status: "Active" },
    { name: "Arthur Osodo Kokwalo", status: "Active" },
    { name: "Samwel Masiwo", status: "Active" },
    { name: "Felix Oyoo", status: "Active" },
    { name: "John Onyango Midira", status: "Active" },
    { name: "Prisca Awino Maganda", status: "Active" },
    { name: "Joshwa Paul", status: "Active" },
    { name: "Reagan Oluoch", status: "Active" },
    { name: "George Otieno Solo", status: "Active" },
    { name: "Samwel Omogi", status: "Active" },
    { name: "Denis Otieno Achapa", status: "Active" },
    { name: "Benard Ooko Rakoro", status: "Active" },
    { name: "Nicholas Otieno Olambo", status: "Active" },
    { name: "Ogolla Awuoti", status: "Active" },
    { name: "Ian Oluoch", status: "Active" },
    { name: "Eliazar Ochola", status: "Active" },
    { name: "Beatrice Okinyi", status: "Active" },
    { name: "Jack Ombaka", status: "Active" },
    { name: "Elekia Ochola Ochieng", status: "Active" },
    { name: "Javan Ngonde", status: "Active" },
    { name: "Teddy Abur", status: "Active" },
    { name: "Renish Kirui", status: "Active" },
    { name: "Jim Kennedy Maziga", status: "Active" },
    { name: "Fredrick Otieno", status: "Active" },
    { name: "Joyce Kerubo Mswanya Nyakiamo", status: "Active" },
    { name: "Pamela Odoyo", status: "Active" },
    { name: "Selemiah Rhiagi", status: "Active" },
    { name: "Vincent Nyatieno", status: "Active" },
    { name: "Jacob Muoga", status: "Active" },
    { name: "Jacob Okomo", status: "Active" },
    { name: "Nancy Oluoch", status: "Active" },
    { name: "Samwel Okeyo Zolombo Ongojo", status: "Active" },
    { name: "Lydia Awuor Ginara", status: "Active" },
    { name: "Eric Otieno Patrobas", status: "Active" },
    { name: "Samuel Ochieng Okal", status: "Active" },
    { name: "Emmanuel Wanyende", status: "Active" },
    { name: "Calvin Ongili", status: "Active" },
    { name: "George Awiru", status: "Active" },
    { name: "Henry Otieno Otunga", status: "Active" },
    { name: "Victor Obiero Warekwa", status: "Active" },
    { name: "Sunny Michael", status: "Active" },
    { name: "Vincent Ochieng", status: "Active" }
  ];
  
  // Function to populate the table
  function populateTable() {
    const tableBody = document.getElementById("membersList");
    tableBody.innerHTML = ""; // Clear existing rows
  
    members.forEach((member, index) => {
      const row = document.createElement("tr");
      row.innerHTML = `
        <td>${index + 1}</td>
        <td>${member.name}</td>
        <td>${member.status}</td>
      `;
      tableBody.appendChild(row);
    });
  }
  
  // Function to filter members by name
  function filterMembers() {
    const searchTerm = document.getElementById("searchInput").value.toLowerCase();
    const filteredMembers = members.filter(member => member.name.toLowerCase().includes(searchTerm));
    const tableBody = document.getElementById("membersList");
    tableBody.innerHTML = ""; // Clear existing rows
  
    filteredMembers.forEach((member, index) => {
      const row = document.createElement("tr");
      row.innerHTML = `
        <td>${index + 1}</td>
        <td>${member.name}</td>
        <td>${member.status}</td>
      `;
      tableBody.appendChild(row);
    });
  }
  
  // Populate the table on page load
  window.onload = populateTable;